// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: Meetstock.proto

package Meetstock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type StockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Meetstock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Meetstock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_Meetstock_proto_rawDescGZIP(), []int{0}
}

func (x *StockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type StockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beef map[string]int32 `protobuf:"bytes,1,rep,name=beef,proto3" json:"beef,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //string message = 1;
}

func (x *StockReply) Reset() {
	*x = StockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Meetstock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReply) ProtoMessage() {}

func (x *StockReply) ProtoReflect() protoreflect.Message {
	mi := &file_Meetstock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReply.ProtoReflect.Descriptor instead.
func (*StockReply) Descriptor() ([]byte, []int) {
	return file_Meetstock_proto_rawDescGZIP(), []int{1}
}

func (x *StockReply) GetBeef() map[string]int32 {
	if x != nil {
		return x.Beef
	}
	return nil
}

type BeefData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beef map[string]int32 `protobuf:"bytes,1,rep,name=beef,proto3" json:"beef,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BeefData) Reset() {
	*x = BeefData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Meetstock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeefData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefData) ProtoMessage() {}

func (x *BeefData) ProtoReflect() protoreflect.Message {
	mi := &file_Meetstock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefData.ProtoReflect.Descriptor instead.
func (*BeefData) Descriptor() ([]byte, []int) {
	return file_Meetstock_proto_rawDescGZIP(), []int{2}
}

func (x *BeefData) GetBeef() map[string]int32 {
	if x != nil {
		return x.Beef
	}
	return nil
}

var File_Meetstock_proto protoreflect.FileDescriptor

var file_Meetstock_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x4d, 0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x4d, 0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x22, 0x0a, 0x0c,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x7a, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x33,
	0x0a, 0x04, 0x62, 0x65, 0x65, 0x66, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4d,
	0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x62,
	0x65, 0x65, 0x66, 0x1a, 0x37, 0x0a, 0x09, 0x42, 0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x76, 0x0a, 0x08,
	0x42, 0x65, 0x65, 0x66, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x04, 0x62, 0x65, 0x65, 0x66,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x73, 0x74, 0x6f,
	0x63, 0x6b, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x65, 0x65, 0x66,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x62, 0x65, 0x65, 0x66, 0x1a, 0x37, 0x0a, 0x09, 0x42,
	0x65, 0x65, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0x48, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x3d, 0x0a, 0x09, 0x4d, 0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x17, 0x2e, 0x4d,
	0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x4d, 0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0c,
	0x5a, 0x0a, 0x2f, 0x4d, 0x65, 0x65, 0x74, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Meetstock_proto_rawDescOnce sync.Once
	file_Meetstock_proto_rawDescData = file_Meetstock_proto_rawDesc
)

func file_Meetstock_proto_rawDescGZIP() []byte {
	file_Meetstock_proto_rawDescOnce.Do(func() {
		file_Meetstock_proto_rawDescData = protoimpl.X.CompressGZIP(file_Meetstock_proto_rawDescData)
	})
	return file_Meetstock_proto_rawDescData
}

var file_Meetstock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Meetstock_proto_goTypes = []interface{}{
	(*StockRequest)(nil), // 0: Meetstock.StockRequest
	(*StockReply)(nil),   // 1: Meetstock.StockReply
	(*BeefData)(nil),     // 2: Meetstock.BeefData
	nil,                  // 3: Meetstock.StockReply.BeefEntry
	nil,                  // 4: Meetstock.BeefData.BeefEntry
}
var file_Meetstock_proto_depIdxs = []int32{
	3, // 0: Meetstock.StockReply.beef:type_name -> Meetstock.StockReply.BeefEntry
	4, // 1: Meetstock.BeefData.beef:type_name -> Meetstock.BeefData.BeefEntry
	0, // 2: Meetstock.Greeter.Meetstock:input_type -> Meetstock.StockRequest
	1, // 3: Meetstock.Greeter.Meetstock:output_type -> Meetstock.StockReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Meetstock_proto_init() }
func file_Meetstock_proto_init() {
	if File_Meetstock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Meetstock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Meetstock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Meetstock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeefData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Meetstock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Meetstock_proto_goTypes,
		DependencyIndexes: file_Meetstock_proto_depIdxs,
		MessageInfos:      file_Meetstock_proto_msgTypes,
	}.Build()
	File_Meetstock_proto = out.File
	file_Meetstock_proto_rawDesc = nil
	file_Meetstock_proto_goTypes = nil
	file_Meetstock_proto_depIdxs = nil
}
